FROM golang:1.26-alpine
WORKDIR /app
RUN apk add --no-cache ca-certificates && \
    go install github.com/air-verse/air@latest && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest && \
    go install github.com/swaggo/swag/cmd/swag@v1.16.4
COPY go.mod go.sum ./
RUN go mod download
EXPOSE 8000
CMD ["sh", "-c", "migrate -path /app/sql/migrations -database $DATABASE_URL up && air"]
