// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: experience.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExperienceSkill = `-- name: AddExperienceSkill :exec
INSERT INTO experience_skills (experience_id, skill_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddExperienceSkillParams struct {
	ExperienceID pgtype.UUID
	SkillID      pgtype.UUID
}

func (q *Queries) AddExperienceSkill(ctx context.Context, arg AddExperienceSkillParams) error {
	_, err := q.db.Exec(ctx, addExperienceSkill, arg.ExperienceID, arg.SkillID)
	return err
}

const countExperience = `-- name: CountExperience :one
SELECT COUNT(*) FROM experience
WHERE
    ($1::text IS NULL OR company ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR role ILIKE '%' || $2::text || '%')
`

type CountExperienceParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
}

func (q *Queries) CountExperience(ctx context.Context, arg CountExperienceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExperience, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExperience = `-- name: CreateExperience :one
INSERT INTO experience (id, company, role, description, start_date, end_date, location)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company, role, description, start_date, end_date, location, created_at, updated_at
`

type CreateExperienceParams struct {
	ID          pgtype.UUID
	Company     string
	Role        string
	Description pgtype.Text
	StartDate   string
	EndDate     pgtype.Text
	Location    pgtype.Text
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.ID,
		arg.Company,
		arg.Role,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExperience = `-- name: DeleteExperience :exec
DELETE FROM experience WHERE id = $1
`

func (q *Queries) DeleteExperience(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExperience, id)
	return err
}

const getExperienceByID = `-- name: GetExperienceByID :one
SELECT id, company, role, description, start_date, end_date, location, created_at, updated_at
FROM experience WHERE id = $1
`

func (q *Queries) GetExperienceByID(ctx context.Context, id pgtype.UUID) (Experience, error) {
	row := q.db.QueryRow(ctx, getExperienceByID, id)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExperience = `-- name: ListExperience :many
SELECT id, company, role, description, start_date, end_date, location, created_at, updated_at
FROM experience
WHERE
    ($1::text IS NULL OR company ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR role ILIKE '%' || $2::text || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListExperienceParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
	Limit   int32
	Offset  int32
}

func (q *Queries) ListExperience(ctx context.Context, arg ListExperienceParams) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listExperience,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Experience
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.Company,
			&i.Role,
			&i.Description,
			&i.StartDate,
			&i.EndDate,
			&i.Location,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExperienceSkills = `-- name: ListExperienceSkills :many
SELECT s.id, s.name, s.category, s.proficiency, s.icon, s.display_order, s.created_at, s.updated_at
FROM skills s
JOIN experience_skills es ON es.skill_id = s.id
WHERE es.experience_id = $1
ORDER BY s.display_order ASC, s.name ASC
`

func (q *Queries) ListExperienceSkills(ctx context.Context, experienceID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listExperienceSkills, experienceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllExperienceSkills = `-- name: RemoveAllExperienceSkills :exec
DELETE FROM experience_skills WHERE experience_id = $1
`

func (q *Queries) RemoveAllExperienceSkills(ctx context.Context, experienceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllExperienceSkills, experienceID)
	return err
}

const removeExperienceSkill = `-- name: RemoveExperienceSkill :exec
DELETE FROM experience_skills WHERE experience_id = $1 AND skill_id = $2
`

type RemoveExperienceSkillParams struct {
	ExperienceID pgtype.UUID
	SkillID      pgtype.UUID
}

func (q *Queries) RemoveExperienceSkill(ctx context.Context, arg RemoveExperienceSkillParams) error {
	_, err := q.db.Exec(ctx, removeExperienceSkill, arg.ExperienceID, arg.SkillID)
	return err
}

const updateExperience = `-- name: UpdateExperience :one
UPDATE experience
SET company = $2, role = $3, description = $4, start_date = $5, end_date = $6,
    location = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, company, role, description, start_date, end_date, location, created_at, updated_at
`

type UpdateExperienceParams struct {
	ID          pgtype.UUID
	Company     string
	Role        string
	Description pgtype.Text
	StartDate   string
	EndDate     pgtype.Text
	Location    pgtype.Text
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, updateExperience,
		arg.ID,
		arg.Company,
		arg.Role,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.Location,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.Company,
		&i.Role,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.Location,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
