// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Experience struct {
	ID          pgtype.UUID
	Company     string
	Role        string
	Description pgtype.Text
	StartDate   string
	EndDate     pgtype.Text
	Location    pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ExperienceSkill struct {
	ExperienceID pgtype.UUID
	SkillID      pgtype.UUID
}

type Project struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	RepoUrl      pgtype.Text
	LiveUrl      pgtype.Text
	ImageUrl     pgtype.Text
	IsFeatured   bool
	DisplayOrder int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type ProjectSkill struct {
	ProjectID pgtype.UUID
	SkillID   pgtype.UUID
}

type Setting struct {
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Skill struct {
	ID           pgtype.UUID
	Name         string
	Category     pgtype.Text
	Proficiency  pgtype.Text
	Icon         pgtype.Text
	DisplayOrder int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Username     string
	Email        string
	Avatar       pgtype.Text
	PasswordHash string
	IsSuper      bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
