// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectSkill = `-- name: AddProjectSkill :exec
INSERT INTO project_skills (project_id, skill_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProjectSkillParams struct {
	ProjectID pgtype.UUID
	SkillID   pgtype.UUID
}

func (q *Queries) AddProjectSkill(ctx context.Context, arg AddProjectSkillParams) error {
	_, err := q.db.Exec(ctx, addProjectSkill, arg.ProjectID, arg.SkillID)
	return err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
WHERE
    ($1::boolean IS NULL OR is_featured = $1)
    AND ($2::text IS NULL OR title ILIKE '%' || $2::text || '%')
`

type CountProjectsParams struct {
	Column1 pgtype.Bool
	Column2 string
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, title, description, repo_url, live_url, image_url, is_featured, display_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, title, description, repo_url, live_url, image_url, is_featured, display_order, created_at, updated_at
`

type CreateProjectParams struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	RepoUrl      pgtype.Text
	LiveUrl      pgtype.Text
	ImageUrl     pgtype.Text
	IsFeatured   bool
	DisplayOrder int32
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.RepoUrl,
		arg.LiveUrl,
		arg.ImageUrl,
		arg.IsFeatured,
		arg.DisplayOrder,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.ImageUrl,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, title, description, repo_url, live_url, image_url, is_featured, display_order, created_at, updated_at
FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.ImageUrl,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectSkills = `-- name: ListProjectSkills :many
SELECT s.id, s.name, s.category, s.proficiency, s.icon, s.display_order, s.created_at, s.updated_at
FROM skills s
JOIN project_skills ps ON ps.skill_id = s.id
WHERE ps.project_id = $1
ORDER BY s.display_order ASC, s.name ASC
`

func (q *Queries) ListProjectSkills(ctx context.Context, projectID pgtype.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listProjectSkills, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description, repo_url, live_url, image_url, is_featured, display_order, created_at, updated_at
FROM projects
WHERE
    ($1::boolean IS NULL OR is_featured = $1)
    AND ($2::text IS NULL OR title ILIKE '%' || $2::text || '%')
ORDER BY display_order ASC, created_at DESC
LIMIT $3 OFFSET $4
`

type ListProjectsParams struct {
	Column1 pgtype.Bool
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.RepoUrl,
			&i.LiveUrl,
			&i.ImageUrl,
			&i.IsFeatured,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllProjectSkills = `-- name: RemoveAllProjectSkills :exec
DELETE FROM project_skills WHERE project_id = $1
`

func (q *Queries) RemoveAllProjectSkills(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeAllProjectSkills, projectID)
	return err
}

const removeProjectSkill = `-- name: RemoveProjectSkill :exec
DELETE FROM project_skills WHERE project_id = $1 AND skill_id = $2
`

type RemoveProjectSkillParams struct {
	ProjectID pgtype.UUID
	SkillID   pgtype.UUID
}

func (q *Queries) RemoveProjectSkill(ctx context.Context, arg RemoveProjectSkillParams) error {
	_, err := q.db.Exec(ctx, removeProjectSkill, arg.ProjectID, arg.SkillID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $2, description = $3, repo_url = $4, live_url = $5, image_url = $6,
    is_featured = $7, display_order = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, repo_url, live_url, image_url, is_featured, display_order, created_at, updated_at
`

type UpdateProjectParams struct {
	ID           pgtype.UUID
	Title        string
	Description  pgtype.Text
	RepoUrl      pgtype.Text
	LiveUrl      pgtype.Text
	ImageUrl     pgtype.Text
	IsFeatured   bool
	DisplayOrder int32
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.RepoUrl,
		arg.LiveUrl,
		arg.ImageUrl,
		arg.IsFeatured,
		arg.DisplayOrder,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RepoUrl,
		&i.LiveUrl,
		&i.ImageUrl,
		&i.IsFeatured,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
