// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettings = `-- name: CreateSettings :one
INSERT INTO settings (
    key,
    value
)
VALUES ($1,$2)
RETURNING key, value
`

type CreateSettingsParams struct {
	Key   string
	Value []byte
}

type CreateSettingsRow struct {
	Key   string
	Value []byte
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (CreateSettingsRow, error) {
	row := q.db.QueryRow(ctx, createSettings, arg.Key, arg.Value)
	var i CreateSettingsRow
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const deleteSettings = `-- name: DeleteSettings :exec
DELETE FROM settings
WHERE key = $1
`

func (q *Queries) DeleteSettings(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSettings, key)
	return err
}

const getSettings = `-- name: GetSettings :many
SELECT 
    key,
    value,
    created_at,
    updated_at
FROM settings
WHERE 
    ($1::text IS NULL OR key ILIKE '%' || $1::text || '%')
    AND ($2::TIMESTAMPTZ IS NULL OR created_at >= $2)
    AND ($3::TIMESTAMPTZ IS NULL OR updated_at >= $3)
LIMIT $4 OFFSET $5
`

type GetSettingsParams struct {
	Column1 string
	Column2 pgtype.Timestamptz
	Column3 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

func (q *Queries) GetSettings(ctx context.Context, arg GetSettingsParams) ([]Setting, error) {
	rows, err := q.db.Query(ctx, getSettings,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSettingsByKey = `-- name: GetSettingsByKey :one
SELECT 
    key, 
    value,
    created_at,
    updated_at
FROM settings
WHERE 
    key = $1
`

func (q *Queries) GetSettingsByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingsByKey, key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET
    value = $1
WHERE 
    key = $2
RETURNING key, value, created_at, updated_at
`

type UpdateSettingsParams struct {
	Value []byte
	Key   string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.Value, arg.Key)
	var i Setting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
