// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSkills = `-- name: CountSkills :one
SELECT COUNT(*)
FROM skills
WHERE
    ($1::text IS NULL OR category = $1)
    AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
`

type CountSkillsParams struct {
	Column1 pgtype.Text
	Column2 string
}

func (q *Queries) CountSkills(ctx context.Context, arg CountSkillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSkills, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (
    id,
    name,
    category,
    proficiency,
    icon,
    display_order
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, category, proficiency, icon, display_order, created_at, updated_at
`

type CreateSkillParams struct {
	ID           pgtype.UUID
	Name         string
	Category     pgtype.Text
	Proficiency  pgtype.Text
	Icon         pgtype.Text
	DisplayOrder int32
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Proficiency,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills
WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT
    id,
    name,
    category,
    proficiency,
    icon,
    display_order,
    created_at,
    updated_at
FROM skills
WHERE id = $1
`

func (q *Queries) GetSkillByID(ctx context.Context, id pgtype.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT 
    id,
    name,
    category,
    proficiency,
    icon,
    display_order,
    created_at,
    updated_at
FROM skills
WHERE name = $1
`

func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT
    id,
    name,
    category,
    proficiency,
    icon,
    display_order,
    created_at,
    updated_at
FROM skills
WHERE
    ($1::text IS NULL OR category = $1)
    AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
ORDER BY display_order ASC, name ASC
LIMIT $3 OFFSET $4
`

type ListSkillsParams struct {
	Column1 pgtype.Text
	Column2 string
	Limit   int32
	Offset  int32
}

func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.Icon,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET
    name = $2,
    category = $3,
    proficiency = $4,
    icon = $5,
    display_order = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, category, proficiency, icon, display_order, created_at, updated_at
`

type UpdateSkillParams struct {
	ID           pgtype.UUID
	Name         string
	Category     pgtype.Text
	Proficiency  pgtype.Text
	Icon         pgtype.Text
	DisplayOrder int32
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Proficiency,
		arg.Icon,
		arg.DisplayOrder,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.Icon,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
