// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    id,
    name,
    username,
    email,
    avatar,
    password_hash,
    is_super
)
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, name, username, email, avatar, is_super, created_at
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Name         string
	Username     string
	Email        string
	Avatar       pgtype.Text
	PasswordHash string
	IsSuper      bool
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Avatar,
		arg.PasswordHash,
		arg.IsSuper,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
    id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    name,
    username,
    email,
    avatar,
    is_super,
    created_at,
    updated_at
FROM
    users
WHERE
    id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    name,
    username,
    email,
    avatar,
    is_super,
    created_at,
    updated_at
FROM
    users
WHERE
    username = $1
`

type GetUserByUsernameRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const giveSuperAccess = `-- name: GiveSuperAccess :one
UPDATE users
SET is_super = $2
WHERE
    id = $1
RETURNING name, username, email, avatar, is_super, updated_at
`

type GiveSuperAccessParams struct {
	ID      pgtype.UUID
	IsSuper bool
}

type GiveSuperAccessRow struct {
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GiveSuperAccess(ctx context.Context, arg GiveSuperAccessParams) (GiveSuperAccessRow, error) {
	row := q.db.QueryRow(ctx, giveSuperAccess, arg.ID, arg.IsSuper)
	var i GiveSuperAccessRow
	err := row.Scan(
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUsers = `-- name: SelectUsers :many
SELECT
    id,
    name,
    username,
    email,
    avatar,
    created_at,
    updated_at
FROM users
WHERE
    ($1::text IS NULL OR id LIKE $1::text || '%')
    AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
    AND ($3::text IS NULL OR username ILIKE '%' || $3::text || '%')
    AND ($4::text IS NULL OR email ILIKE '%' || $4::text || '%')
    AND ($5::boolean IS NULL OR is_super = $5)
    AND ($6::timestamptz IS NULL OR created_at >= $6)
    AND ($7::timestamptz IS NULL OR updated_at >= $7)
LIMIT $8 OFFSET $9
`

type SelectUsersParams struct {
	Column1 string
	Column2 string
	Column3 string
	Column4 string
	Column5 bool
	Column6 pgtype.Timestamptz
	Column7 pgtype.Timestamptz
	Limit   int32
	Offset  int32
}

type SelectUsersRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SelectUsers(ctx context.Context, arg SelectUsersParams) ([]SelectUsersRow, error) {
	rows, err := q.db.Query(ctx, selectUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectUsersRow
	for rows.Next() {
		var i SelectUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Avatar,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET password_hash = $2
WHERE
    id = $1
RETURNING id, name, username, email, avatar, is_super, updated_at
`

type UpdatePasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

type UpdatePasswordRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UpdatePasswordRow, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.ID, arg.PasswordHash)
	var i UpdatePasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    name = $2,
    username = $3,
    email = $4,
    avatar = $5,
    updated_at = NOW()
WHERE
    id = $1 
RETURNING id, name, username, email, avatar, is_super, updated_at
`

type UpdateUserParams struct {
	ID       pgtype.UUID
	Name     string
	Username string
	Email    string
	Avatar   pgtype.Text
}

type UpdateUserRow struct {
	ID        pgtype.UUID
	Name      string
	Username  string
	Email     string
	Avatar    pgtype.Text
	IsSuper   bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Avatar,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Avatar,
		&i.IsSuper,
		&i.UpdatedAt,
	)
	return i, err
}
